/*
567. Leetcode coding challenge: Permutation in string

Given two strings s1 and s2, write a function to return true if s2 contains the
permutation of s1. In other words, one of the first string's permutations is the
substring of the second string.

Example 1:

Input:  s1 = "ab" s2 = "eidbaooo"
Output: true
Explanation: s2 contains one permutation of s1 ("ba").

Example 2:

Input:  s1= "ab" s2 = "eidboaoo"
Output: false

Note:

    The input strings only contain lower case letters.
    The length of both given strings is in range [1, 10,000].

*/

#include <iomanip>
#include <iostream>
#include <string>
#include <unordered_set>
#include <vector>

using namespace std;

class Solution {
  size_t src_len;
  size_t needle_len;
  string dst_str;
  vector<int> visited_indices;
  unordered_set<string> already_visited_needles;
  int end_search;

  bool check_if_src_contains_permutation_of_needle(const string& src,
                                                   const string& needle) {
    for (size_t i{}; !end_search && i < needle_len; i++) {
      if (visited_indices[i])
        continue;

      visited_indices[i] = 1;
      dst_str.push_back(needle[i]);

      if (already_visited_needles.count(dst_str)) {
        dst_str.pop_back();
        visited_indices[i] = 0;
        continue;
       }

      already_visited_needles.insert(dst_str);

      const size_t s2_needle_offset{src.find(dst_str)};

      if (string::npos == s2_needle_offset) {
        if (1 == dst_str.size()) {
          end_search = 1;
          return false;
        }

        dst_str.pop_back();
        visited_indices[i] = 0;
        continue;
      }

      if (dst_str.length() == needle_len)
        return true;

      if (s2_needle_offset + needle_len <= src_len) {
        if (check_if_src_contains_permutation_of_needle(src, needle))
          return true;
      }

      dst_str.pop_back();
      visited_indices[i] = 0;
    }

    return false;
  }

 public:
  bool checkInclusion(const string& s1, const string& s2) {
    src_len = s2.length();
    needle_len = s1.length();
    if (needle_len > src_len)
      return false;
    if (string::npos != s2.find(s1))
      return true;

    dst_str.clear();
    dst_str.reserve(needle_len);
    visited_indices.clear();
    visited_indices.resize(needle_len, 0);
    already_visited_needles.clear();
    end_search = 0;
    return check_if_src_contains_permutation_of_needle(s2, s1);
  }
};

int main() {
  Solution s{};
  cout << boolalpha << "s.checkInclusion(\"ab\", \"eidbaooo\") -> "
       << s.checkInclusion("ab", "eidbaooo") << '\n';  // expected output: true
  cout << "s.checkInclusion(\"ab\", \"eidboaoo\") -> "
       << s.checkInclusion("ab", "eidboaoo") << '\n';  // expected output: false
  cout << "s.checkInclusion(\"trinitrophenylmethylnitramine\", "
          "\"dinitrophenylhydrazinetrinitrophenylmethylnitramine\") -> "
       << s.checkInclusion(
              "trinitrophenylmethylnitramine",
              "dinitrophenylhydrazinetrinitrophenylmethylnitramine")
       << '\n';  // expected output: true
  cout << "s.checkInclusion(\"adc\", "
          "\"dcda\") -> "
       << s.checkInclusion("adc", "dcda") << '\n';  // expected output: true

  string s1{
      "kuzntqeuvaszrspkgjvxrupwxwrexztptsowceibeewxbslvosbobmyymikdscshybtmanu"
      "xeqtanrjekbwirmhgvfmzipfiqxcilarfyasoayepgfzmdytlpjymeaztsyubkbmblepwoz"
      "ffxiitdhwaquozlfmnascomqczrbhxcnzugppddtudxrigfeaozzojpeamnobapgwksudbi"
      "wdedvprwonmzardsodhxmkgghqzfhorjaijdvwzsnfpdfklwibbsnwqsoajcpjisbgizgtt"
      "lnmclawbgnhbmtcpuusuammvgxnopdngclxumgfgwjrinamevhirpmlkwtyxkrmoffrreot"
      "dosjghsrkgxyiyrytbbofgczndgmdalyvvoljczcztxitxelywqemjigtuanubpstndwzvt"
      "iejtoqvetaehvcuujyupncumjnkesmoadzyvkwvjqgqewvvvpheyyvkewefbjjqzajxnhou"
      "odanyruqpzdcjmgnxkmhsgqjhpcyviewmrkfioudzqivmmguxjxuxdmpsmkwnvbxcomifgx"
      "qmcovlkooptjpfxjllwtlkkoaayzduodgsusaogswmoqkznynwiukkrrxzkwcknwlazxnlm"
      "ghybxmyvquzbdqlpfydhnnuvlmyjmixyzso"};
  cout << "s.checkInclusion("
          "\"kuzntqeuvaszrspkgjvxrupwxwrexztptsowceibeewxbslvosbobmyymikdscshy"
          "b"
          "tmanuxeqtanrjekbwirmhgvfmzipfiqxcilarfyasoayepgfzmdytlpjymeaztsyubk"
          "b"
          "mblepwozffxiitdhwaquozlfmnascomqczrbhxcnzugppddtudxrigfeaozzojpeamn"
          "o"
          "bapgwksudbiwdedvprwonmzardsodhxmkgghqzfhorjaijdvwzsnfpdfklwibbsnwqs"
          "o"
          "ajcpjisbgizgttlnmclawbgnhbmtcpuusuammvgxnopdngclxumgfgwjrinamevhirp"
          "m"
          "lkwtyxkrmoffrreotdosjghsrkgxyiyrytbbofgczndgmdalyvvoljczcztxitxelyw"
          "q"
          "emjigtuanubpstndwzvtiejtoqvetaehvcuujyupncumjnkesmoadzyvkwvjqgqewvv"
          "v"
          "pheyyvkewefbjjqzajxnhouodanyruqpzdcjmgnxkmhsgqjhpcyviewmrkfioudzqiv"
          "m"
          "mguxjxuxdmpsmkwnvbxcomifgxqmcovlkooptjpfxjllwtlkkoaayzduodgsusaogsw"
          "m"
          "oqkznynwiukkrrxzkwcknwlazxnlmghybxmyvquzbdqlpfydhnnuvlmyjmixyzso\","
          "\"zthosfejqodcstlqczkndmgwtcakxzxaklkrehkfwnokclametzpnblcwaspdblfo"
          "o"
          "psiqrpzlbmlysddlqxcjzezcpknwzljvhmqxqinmptcppipifchxexlytleambzwmqw"
          "g"
          "vxlehnecdqsqbrxqfwvcovgdvtmwbnvajvkizixbmuiuyuixjhiohimghdbohetogrh"
          "z"
          "sbzgpekosxcjglsrvzenovpjyzknuumpsdrufcjsyfbuwfmaaztxjbpjctnuwcqknne"
          "m"
          "ptjbgfthyafeatskfmysaioqikcpywmefujnvthumyhareltknxyvqprexgbwyzodfk"
          "i"
          "nltwobeukrmpyjkrgvwhbtnzaozgxouxndmkyvzlujhxxwebptykctbojgnvcwhhgsy"
          "o"
          "hccrqxksdyygcwdsazlznhqjdddisjmfqvjqcquuvjrzkcvzpxpfakbkrqlzacanqbg"
          "g"
          "avezedqmoffxmkrlcwxdeosvhvvknqimwpasrlldewvhppzixgcxisysgeppcwfknec"
          "u"
          "pyrrqnkhvessintrequaqiuoesgyndovaqxnlldmdupjcjzejannfjfasguyvgsdakw"
          "x"
          "ezrginhdstbrtqmznpkasytqtbfyftwhgnuazcwehsvcdukuifmkefzabxyhihgnldp"
          "s"
          "vglubalbsvqstfxehvnpxmrejnkqacafuvzghbttgqmjhqzejasoasbpjirfawcvwah"
          "y"
          "kvrfpaadcgvxssebdznzyvamyilahahgdslwvpuvzsinbbqecdqyvwnucjzyxmxwqwy"
          "x"
          "bxoljnjcqqdumghmcvqpcpjlxemupospxvkicqvyiavatbojgzurfzitgpeqjmvsgzz"
          "q"
          "phciyweyavebslgegjcyqmgehchryyclswjequeijzpsvuercqzhwgtgyxhxavhqkrw"
          "q"
          "dvkqvklicxpasnsnbgybtufdgbwrpaewzwczabckvddtewunsktcznqkivsubdjrpzx"
          "t"
          "sohiilcybrwqtlfqmjzmvpbfjmbjvbpwietkyzwzizwuiohjuhoekejhmkrooeyydma"
          "v"
          "dencmxhsxdnyitzivlymzyqogdhzrwhbdupborzqihurziajjwbrfwkzgbpmfgtobkb"
          "z"
          "yijcgkszyuyouyxvztmmtaqetcaxqrkbrmkzyokglckifgdfidjqoiqrfrpftagxxoq"
          "o"
          "dbyygdioxdznycssxjvpotsrptttrbjayhugecptuibezsyggqcyvzosvmlpwmnuhov"
          "v"
          "hfyazkdrfxlxjxpbkkbuexxnklhnkteyjshhlojnbxtyltdfzhulcsptinpsskaeowo"
          "f"
          "ruejqpinhivlpvvosppxtbbrebvfihmamdlvsjirwfzhzmaqzuryakjlzroxrlwccda"
          "n"
          "nvzwenabvosplnwhotxyzxhocdnvsekmnepzzqjhqrokocqewpihhyftshsfehijlvp"
          "a"
          "jrcrgeqqjigmzkrhcgafqkdkrkkyausijdfzqewawxurtzhioqqnoxhbrdrriveapde"
          "b"
          "bwbrnmpcakomfhpfrqvzmpqkqucoepjklaqtirgkcrgpdhvyxybnulrchqgbupjdxxa"
          "l"
          "bwljfpdjfnlqfquhdxvvuaecgzgfhulhkkvpuexpssodxqxhrbpzzgdiohxzjxnuhta"
          "v"
          "littooxkuededfxdaabuzdlwjhitwykqdvtrwuohpvpgpeudhpslpvxmotibojtgvoh"
          "q"
          "aaowiofdtgbkiiurhcfavlgsnqxndcxyxozklduxqeovzrtwuhoikgpyqoqwllagzuf"
          "k"
          "uzntqeuvaszrspkgjvxrupwxwrexztptsowceibeewxbslvosbobmyymikdscshybtm"
          "a"
          "nuxeqtanrjekbwirmhgvfmzipfiqxcilarfyfsoayepgfzmdytlpjymeaztsyubkbmb"
          "l"
          "epwozffxiitdhwaquozlfmnascomqczrbhxcnzugppddtudxrigfeaozzojpeamnoba"
          "p"
          "gwksudbmwdedvprwonmzardsodhxmkgghqzfhorjaijdvwzsnfpdfklwibbsnwqsoaj"
          "c"
          "pjisbgizgttlnmclawbgnhbmtcpuusuamivgxnopdngclxumgfgwjrinamevhirpmlk"
          "w"
          "tyxkrmoafrreotdosjghsrkgxyiyrytbbofgczndgmdalyvvoljczcztxitxelywqem"
          "j"
          "igtuanubpstndwzvtiejtoqvetaehvcuujyupncumjnkesmoadzyvkwvjqgqewvvvph"
          "e"
          "yyvkewefbjjqzajxnhouodanyruqpzdcjmgnxkmhsgqjhpcyviewmrkfioudzqivmmg"
          "u"
          "xjxuxdmpsmkwnvbxcomifgxqmcovlkooptjpfxjllwtlkkoaayzduodgsusaogswmoq"
          "k"
          "znynyiukkrrxzkwcknwlazxnlmghybxmyvquzbdqlpfydhnnuvlmyjmixwzsoufvjlr"
          "q"
          "tzxvybzhurdqdtnkciiradptqxzgrkqgfbnsmptyyggwpenatlrtpvmdpveivmenzwj"
          "l"
          "wdhlhmmpvbglhxcinvhhcphgklicwwnwqbkbndiuqowwgzdczwvlazndbboublzrltx"
          "a"
          "hxenivmkbwofrnkkvjixfbbctshvqzmgwqrmheupodlrnebsidrbxxjfeoqgcoscymz"
          "s"
          "kvbamtxtpumbdmedjghxazwamkqdrxsqytqxkrrqcnwrtkuaocuwmyucctdnaqfjlos"
          "o"
          "vveoxjyypqrbkflxrrxlnjxhkrrvjettqfzzbwbzowsufxmppazhwiwcvimmlixdzgp"
          "m"
          "fayrblbkulfopwarxlsbfkuqvhyufwdswfpxqwhuvepyslbliapotofrxhufoopqhqj"
          "c"
          "jdtleeoedsacpeqfewxehghwvfvqmlzvzudkqxinsfekpbaggbpohbtbhcvdzvuormp"
          "z"
          "adkhhqqyspfkijjcelofwgkgimjxrkwqwhpqfihyhmwdkwhathcxvxtuopufsjaagba"
          "m"
          "ghtsjewrpooxrprtvqpslsbaijrzojgwhekijtfugwbvgdltgpentcyjbwqjcdqkhic"
          "b"
          "sdvgtvsecpsacesztkjdskoumcheqzmoijoimnmnhfavttfamkkvugpmnibdzhcieyh"
          "h"
          "ctifhbvqrllslpvymjamfmgladmpeqdrtumbqwcwwkduavjokhjrdbdozxaqemvurjw"
          "d"
          "ukuwrbzfstuesjqfgblvvaqemylqgrtfzdrfgtcbvaokygyidfsbppasppzcunjwbrh"
          "q"
          "scumnrugeyxqvceninwsvmqcekvuetloevkrntgsrivpebgoobcggmgwkrzagkdavpe"
          "j"
          "dgkpokcdpvncsmduzhowhdjklqwyphevtaugcabxovxgjovvgzksukpnadsblbpnuui"
          "h"
          "xdkovwsmniptwhrjxhyitozdwgkdkasspklxbyfmmugmawjflmrdiqmolsufpyzkrrq"
          "r"
          "vgnbtcogomdjrymxgnocnmpsdmbncterfrrxqyrsdqjzrodttnjbblleexyvfzxemlx"
          "f"
          "mxbzffflpyifrqhbdnwpuuwfhskfevjshsxvhvbldqyxenpxkvamashnbmrfiladqnu"
          "z"
          "wltrkoegwxrjveajpyvchyotakniwcyigejnaspdfjssacnfhbyobgrovavxoclvkgv"
          "g"
          "ivoiycquftjuqynabeqakugedwlogqfbbivbzisljreuowaxfaugjunbyrcxvlqjvvu"
          "e"
          "wgprwfiofxyzdaomzjfystxrbpmgdwyznnuzibozcjtsxxastlhmjpogvuhdtfhnmrh"
          "d"
          "xihhrtxqocmsmysxuudsdquadshqncpbejkjarbhkwkstpcqgwuarnmvtfjvdzeeklw"
          "n"
          "njdewmwdyzdfnryaqoiysysfvlxetggjhywxwvkvvuccklxptokzvrrhodicekjrffb"
          "d"
          "jxoftxbstcbxjcksqcvcwkisywdzepzgznaorlllmahrqepouqnrtbhgxnsnyhkacxh"
          "j"
          "zgvxhlukbvspfzqgguqkngncotvgvuygijtkucvqcsjjolodnbfeznuikkaghyyqtxm"
          "t"
          "djchrgybirzkbysbgnwwqaxjsnneazxnmdyzooizcyqtxlmqvujoqhjqlnuvojlkcdy"
          "b"
          "fryidsunirmymtvltnjiggwxeqowcnbukotbngjaidyvhmobdxlklwqxshkaphxwdxz"
          "o"
          "nqddvstwrrtatklpujldtgrofxyunlmlwquruzekmdymzhpuuuaiyinmaedxxhhayzy"
          "b"
          "sepcohcrymkysdaeagmhodvkoissnegjecmtnbydbakamurdqwwgqqfbefltdkdvyld"
          "j"
          "xynweicudbwirebvzknodfkycidoqaalxorwlvnosvcpudvsiljwlmfqpvwtbjeyyde"
          "x"
          "vfmkiilwlxcpnogyeyspjaumcbrgxkeeezgyrbmtkotoyjnedraupxevwjcluyxdctf"
          "a"
          "zusyqeklxpotczvkphllcgfrykpuwscfknqhfkxdihdkymiqizppipnbflfhduzjgvo"
          "e"
          "hhvtqolybcshofasguaaeaakcsxqsqxpuydzhndleoxgmkrtlivudapfhefocneliic"
          "m"
          "rtishcmxmcdskyedbqppswqnesziwankobhaxklswulygdojhpobyezjzyengtfulym"
          "y"
          "bqiodmkirqpggycyouzqhrexnntvnlhhokdyzvudgilvqpjkeactaivsjdwfesruuse"
          "w"
          "lpscumpqslulwrhramanthuogjdadmqjeccbutdfexdcsbqujpqdlryelnzvfbncraj"
          "i"
          "cdnomidvmspjljjzglnahdmrctedjzdtozllmmyeamctrcyrzzdzwvfqgjfstbtitgm"
          "e"
          "ogjpgllpihylxgupxxqmheusrglbampwrhtejoqqjkcljmppmemguapopatjkbzomwe"
          "g"
          "krwxblxgymfmurhfokjkhljtxosxtgmaldrjjhxrcvuddvzlamavxpzszsrfepfsuka"
          "d"
          "tnwyzhwdergrofmetngzuifiuonziduvucichmxhmxrulpykwedymiycbhcsvrkctvq"
          "q"
          "fvygtlyhlqbrwvmbgnwlryeotjkvowxmdlyjhyvtvyognldmsxqlotfzvxrmdultwbs"
          "n"
          "stmjakjaqqpfurvwturqyzcnfkoxumuquwgpersslowdvrnssqcgwmfnssvtobdwcsc"
          "o"
          "ikoythwhsxswsmsimntribaohzrmjculdnnguchmqgyzqeipuumwgizlvjmpvyotgzm"
          "t"
          "santswdarbyaklpiclafgqdaoeiitxlcpwhlqsidkb\") -> "
       << s.checkInclusion(s1,
                           "zthosfejqodcstlqczkndmgwtcakxzxaklkrehkfwnokclamet"
                           "zpnblcwaspdblf"
                           "oopsiqrpzlbmlysddlqxcjzezcpknwzljvhmqxqinmptcppipi"
                           "fchxexlytleamb"
                           "zwmqwgvxlehnecdqsqbrxqfwvcovgdvtmwbnvajvkizixbmuiu"
                           "yuixjhiohimghd"
                           "bohetogrhzsbzgpekosxcjglsrvzenovpjyzknuumpsdrufcjs"
                           "yfbuwfmaaztxjb"
                           "pjctnuwcqknnemptjbgfthyafeatskfmysaioqikcpywmefujn"
                           "vthumyhareltkn"
                           "xyvqprexgbwyzodfkinltwobeukrmpyjkrgvwhbtnzaozgxoux"
                           "ndmkyvzlujhxxw"
                           "ebptykctbojgnvcwhhgsyohccrqxksdyygcwdsazlznhqjdddi"
                           "sjmfqvjqcquuvj"
                           "rzkcvzpxpfakbkrqlzacanqbggavezedqmoffxmkrlcwxdeosv"
                           "hvvknqimwpasrl"
                           "ldewvhppzixgcxisysgeppcwfknecupyrrqnkhvessintrequa"
                           "qiuoesgyndovaq"
                           "xnlldmdupjcjzejannfjfasguyvgsdakwxezrginhdstbrtqmz"
                           "npkasytqtbfyft"
                           "whgnuazcwehsvcdukuifmkefzabxyhihgnldpsvglubalbsvqs"
                           "tfxehvnpxmrejn"
                           "kqacafuvzghbttgqmjhqzejasoasbpjirfawcvwahykvrfpaad"
                           "cgvxssebdznzyv"
                           "amyilahahgdslwvpuvzsinbbqecdqyvwnucjzyxmxwqwyxbxol"
                           "jnjcqqdumghmcv"
                           "qpcpjlxemupospxvkicqvyiavatbojgzurfzitgpeqjmvsgzzq"
                           "phciyweyavebsl"
                           "gegjcyqmgehchryyclswjequeijzpsvuercqzhwgtgyxhxavhq"
                           "krwqdvkqvklicx"
                           "pasnsnbgybtufdgbwrpaewzwczabckvddtewunsktcznqkivsu"
                           "bdjrpzxtsohiil"
                           "cybrwqtlfqmjzmvpbfjmbjvbpwietkyzwzizwuiohjuhoekejh"
                           "mkrooeyydmavde"
                           "ncmxhsxdnyitzivlymzyqogdhzrwhbdupborzqihurziajjwbr"
                           "fwkzgbpmfgtobk"
                           "bzyijcgkszyuyouyxvztmmtaqetcaxqrkbrmkzyokglckifgdf"
                           "idjqoiqrfrpfta"
                           "gxxoqodbyygdioxdznycssxjvpotsrptttrbjayhugecptuibe"
                           "zsyggqcyvzosvm"
                           "lpwmnuhovvhfyazkdrfxlxjxpbkkbuexxnklhnkteyjshhlojn"
                           "bxtyltdfzhulcs"
                           "ptinpsskaeowofruejqpinhivlpvvosppxtbbrebvfihmamdlv"
                           "sjirwfzhzmaqzu"
                           "ryakjlzroxrlwccdannvzwenabvosplnwhotxyzxhocdnvsekm"
                           "nepzzqjhqrokoc"
                           "qewpihhyftshsfehijlvpajrcrgeqqjigmzkrhcgafqkdkrkky"
                           "ausijdfzqewawx"
                           "urtzhioqqnoxhbrdrriveapdebbwbrnmpcakomfhpfrqvzmpqk"
                           "qucoepjklaqtir"
                           "gkcrgpdhvyxybnulrchqgbupjdxxalbwljfpdjfnlqfquhdxvv"
                           "uaecgzgfhulhkk"
                           "vpuexpssodxqxhrbpzzgdiohxzjxnuhtavlittooxkuededfxd"
                           "aabuzdlwjhitwy"
                           "kqdvtrwuohpvpgpeudhpslpvxmotibojtgvohqaaowiofdtgbk"
                           "iiurhcfavlgsnq"
                           "xndcxyxozklduxqeovzrtwuhoikgpyqoqwllagzufkuzntqeuv"
                           "aszrspkgjvxrup"
                           "wxwrexztptsowceibeewxbslvosbobmyymikdscshybtmanuxe"
                           "qtanrjekbwirmh"
                           "gvfmzipfiqxcilarfyfsoayepgfzmdytlpjymeaztsyubkbmbl"
                           "epwozffxiitdhw"
                           "aquozlfmnascomqczrbhxcnzugppddtudxrigfeaozzojpeamn"
                           "obapgwksudbmwd"
                           "edvprwonmzardsodhxmkgghqzfhorjaijdvwzsnfpdfklwibbs"
                           "nwqsoajcpjisbg"
                           "izgttlnmclawbgnhbmtcpuusuamivgxnopdngclxumgfgwjrin"
                           "amevhirpmlkwty"
                           "xkrmoafrreotdosjghsrkgxyiyrytbbofgczndgmdalyvvoljc"
                           "zcztxitxelywqe"
                           "mjigtuanubpstndwzvtiejtoqvetaehvcuujyupncumjnkesmo"
                           "adzyvkwvjqgqew"
                           "vvvpheyyvkewefbjjqzajxnhouodanyruqpzdcjmgnxkmhsgqj"
                           "hpcyviewmrkfio"
                           "udzqivmmguxjxuxdmpsmkwnvbxcomifgxqmcovlkooptjpfxjl"
                           "lwtlkkoaayzduo"
                           "dgsusaogswmoqkznynyiukkrrxzkwcknwlazxnlmghybxmyvqu"
                           "zbdqlpfydhnnuv"
                           "lmyjmixwzsoufvjlrqtzxvybzhurdqdtnkciiradptqxzgrkqg"
                           "fbnsmptyyggwpe"
                           "natlrtpvmdpveivmenzwjlwdhlhmmpvbglhxcinvhhcphgklic"
                           "wwnwqbkbndiuqo"
                           "wwgzdczwvlazndbboublzrltxahxenivmkbwofrnkkvjixfbbc"
                           "tshvqzmgwqrmhe"
                           "upodlrnebsidrbxxjfeoqgcoscymzskvbamtxtpumbdmedjghx"
                           "azwamkqdrxsqyt"
                           "qxkrrqcnwrtkuaocuwmyucctdnaqfjlosovveoxjyypqrbkflx"
                           "rrxlnjxhkrrvje"
                           "ttqfzzbwbzowsufxmppazhwiwcvimmlixdzgpmfayrblbkulfo"
                           "pwarxlsbfkuqvh"
                           "yufwdswfpxqwhuvepyslbliapotofrxhufoopqhqjcjdtleeoe"
                           "dsacpeqfewxehg"
                           "hwvfvqmlzvzudkqxinsfekpbaggbpohbtbhcvdzvuormpzadkh"
                           "hqqyspfkijjcel"
                           "ofwgkgimjxrkwqwhpqfihyhmwdkwhathcxvxtuopufsjaagbam"
                           "ghtsjewrpooxrp"
                           "rtvqpslsbaijrzojgwhekijtfugwbvgdltgpentcyjbwqjcdqk"
                           "hicbsdvgtvsecp"
                           "sacesztkjdskoumcheqzmoijoimnmnhfavttfamkkvugpmnibd"
                           "zhcieyhhctifhb"
                           "vqrllslpvymjamfmgladmpeqdrtumbqwcwwkduavjokhjrdbdo"
                           "zxaqemvurjwduk"
                           "uwrbzfstuesjqfgblvvaqemylqgrtfzdrfgtcbvaokygyidfsb"
                           "ppasppzcunjwbr"
                           "hqscumnrugeyxqvceninwsvmqcekvuetloevkrntgsrivpebgo"
                           "obcggmgwkrzagk"
                           "davpejdgkpokcdpvncsmduzhowhdjklqwyphevtaugcabxovxg"
                           "jovvgzksukpnad"
                           "sblbpnuuihxdkovwsmniptwhrjxhyitozdwgkdkasspklxbyfm"
                           "mugmawjflmrdiq"
                           "molsufpyzkrrqrvgnbtcogomdjrymxgnocnmpsdmbncterfrrx"
                           "qyrsdqjzrodttn"
                           "jbblleexyvfzxemlxfmxbzffflpyifrqhbdnwpuuwfhskfevjs"
                           "hsxvhvbldqyxen"
                           "pxkvamashnbmrfiladqnuzwltrkoegwxrjveajpyvchyotakni"
                           "wcyigejnaspdfj"
                           "ssacnfhbyobgrovavxoclvkgvgivoiycquftjuqynabeqakuge"
                           "dwlogqfbbivbzi"
                           "sljreuowaxfaugjunbyrcxvlqjvvuewgprwfiofxyzdaomzjfy"
                           "stxrbpmgdwyznn"
                           "uzibozcjtsxxastlhmjpogvuhdtfhnmrhdxihhrtxqocmsmysx"
                           "uudsdquadshqnc"
                           "pbejkjarbhkwkstpcqgwuarnmvtfjvdzeeklwnnjdewmwdyzdf"
                           "nryaqoiysysfvl"
                           "xetggjhywxwvkvvuccklxptokzvrrhodicekjrffbdjxoftxbs"
                           "tcbxjcksqcvcwk"
                           "isywdzepzgznaorlllmahrqepouqnrtbhgxnsnyhkacxhjzgvx"
                           "hlukbvspfzqggu"
                           "qkngncotvgvuygijtkucvqcsjjolodnbfeznuikkaghyyqtxmt"
                           "djchrgybirzkby"
                           "sbgnwwqaxjsnneazxnmdyzooizcyqtxlmqvujoqhjqlnuvojlk"
                           "cdybfryidsunir"
                           "mymtvltnjiggwxeqowcnbukotbngjaidyvhmobdxlklwqxshka"
                           "phxwdxzonqddvs"
                           "twrrtatklpujldtgrofxyunlmlwquruzekmdymzhpuuuaiyinm"
                           "aedxxhhayzybse"
                           "pcohcrymkysdaeagmhodvkoissnegjecmtnbydbakamurdqwwg"
                           "qqfbefltdkdvyl"
                           "djxynweicudbwirebvzknodfkycidoqaalxorwlvnosvcpudvs"
                           "iljwlmfqpvwtbj"
                           "eyydexvfmkiilwlxcpnogyeyspjaumcbrgxkeeezgyrbmtkoto"
                           "yjnedraupxevwj"
                           "cluyxdctfazusyqeklxpotczvkphllcgfrykpuwscfknqhfkxd"
                           "ihdkymiqizppip"
                           "nbflfhduzjgvoehhvtqolybcshofasguaaeaakcsxqsqxpuydz"
                           "hndleoxgmkrtli"
                           "vudapfhefocneliicmrtishcmxmcdskyedbqppswqnesziwank"
                           "obhaxklswulygd"
                           "ojhpobyezjzyengtfulymybqiodmkirqpggycyouzqhrexnntv"
                           "nlhhokdyzvudgi"
                           "lvqpjkeactaivsjdwfesruusewlpscumpqslulwrhramanthuo"
                           "gjdadmqjeccbut"
                           "dfexdcsbqujpqdlryelnzvfbncrajicdnomidvmspjljjzglna"
                           "hdmrctedjzdtoz"
                           "llmmyeamctrcyrzzdzwvfqgjfstbtitgmeogjpgllpihylxgup"
                           "xxqmheusrglbam"
                           "pwrhtejoqqjkcljmppmemguapopatjkbzomwegkrwxblxgymfm"
                           "urhfokjkhljtxo"
                           "sxtgmaldrjjhxrcvuddvzlamavxpzszsrfepfsukadtnwyzhwd"
                           "ergrofmetngzui"
                           "fiuonziduvucichmxhmxrulpykwedymiycbhcsvrkctvqqfvyg"
                           "tlyhlqbrwvmbgn"
                           "wlryeotjkvowxmdlyjhyvtvyognldmsxqlotfzvxrmdultwbsn"
                           "stmjakjaqqpfur"
                           "vwturqyzcnfkoxumuquwgpersslowdvrnssqcgwmfnssvtobdw"
                           "cscoikoythwhsx"
                           "swsmsimntribaohzrmjculdnnguchmqgyzqeipuumwgizlvjmp"
                           "vyotgzmtsantsw"
                           "darbyaklpiclafgqdaoeiitxlcpwhlqsidkb")
       << '\n';  // expected output: true

  s1 = "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopq"
       "rs"
       "tuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghij"
       "kl"
       "mnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabc"
       "de"
       "fghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuv"
       "wx"
       "yzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmno"
       "pq"
       "rstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh"
       "ij"
       "klmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyza"
       "bc"
       "def";
  cout << "s.checkInclusion("
          "\"abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijkl"
          "mn"
          "opqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzab"
          "cd"
          "efghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqr"
          "st"
          "uvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefgh"
          "ij"
          "klmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwx"
          "yz"
          "abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmn"
          "op"
          "qrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcd"
          "ef"
          "ghijklmnopqrstuvwxyzabcdef\", "
          "\"bcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklm"
          "no"
          "pqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabc"
          "de"
          "fghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrs"
          "tu"
          "vwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghi"
          "jk"
          "lmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxy"
          "za"
          "bcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmno"
          "pq"
          "rstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcde"
          "fg"
          "hijklmnopqrstuvwxyzabcdefg\") -> "
       << s.checkInclusion(
              s1,
              "bcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijk"
              "lm"
              "nopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvw"
              "xy"
              "zabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghi"
              "jk"
              "lmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstu"
              "vw"
              "xyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefg"
              "hi"
              "jklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrs"
              "tu"
              "vwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcde"
              "fg"
              "hijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefg")
       << '\n';  // expected output: true

  s1 = "xuumbjffxuzovdwrnolopeingppzgorotzdqfprokkmucxwsub";
  cout
      << "s.checkInclusion("
         "\"xuumbjffxuzovdwrnolopeingppzgorotzdqfprokkmucxwsub\","
         "\"jpdojwinknmyeorfdhpsysyealozhgbapagzjsivbxmcyijlbdafupblrawguoazuzc"
         "qupobxayrkpqxawytdsdznljnxulaugewrbjmkslsrllixpkuvorhnnhkzikovsajrbhj"
         "dybocvjloqiikidsnwcubhliajwwqkpqaugidhfxqfxrkluvadcdmekdhckszpojvwpiq"
         "uazmaecaxxwsnswzxbctqeqhjsrgnjsjmaqbexexuwgfglixsthifevokdgexxkdmzaxr"
         "cilmthzemuomexwzipzivdyxqnvgzpjavonrkobmgkormdmfiwwalgdzwlngkrjmdwkkn"
         "ajqatghoddybqfkorhpmrkfcfwsaproaenfedvfendprnlpmuqklsqrsjuejyxulfuhds"
         "yolthhhfhmxorojnjsvqyworupkdzhyqkzikvhltfsrhrecmyyddtinphjsmmbdtrouyi"
         "fvsvvlamwhkffrrywdiawpvxwcwfkcunbjaelbcmdwczikkfelahowtbwqbdcjggnmknf"
         "hjdtusfjotsbjgtlnuonlxjlcwyqiffktonvtrkcogosfbcvcosktnvbeitxuqpexxejn"
         "klndzbtzlzeebwufoiwqqcoemnshcpovntjgidophekyntcsrwzvovwmostqudxgeaowe"
         "hcmqmdrllovmmbgqhaxrqluizhhhslystwkhckjtosnomfvyibkasycxnnmvkbwkbhzea"
         "yezughsmqovogrnihjgetsdvhymjmnijzwvpasurcaybmyzfbqepjsdqwmkmomzkociaq"
         "tnkwiguylhwxrfamyxjvfxwonwblidvcsenvwigjjqdsnnydlgdhlsdtonvuapzaozkdt"
         "yiartimmpwgotnwpiwimbdunqfickerusbvrqwazvnwgdczvnqtigjmkjgsridfulxjek"
         "azzqkdynyuutyoffhntfbcruhrmnhhjyyzfszbaqykgnroepiovqqlhdtkizvpivukdut"
         "itwzhapvcyfghqvtjyyrdbctvdccoxjtsovdosbyqaiffumnrfokrbgvedxbcytvbcaeo"
         "viutdmxwfhxgchnusazcztitxgyjrkjdmajbndlemsnpjwzgvpitrfrjoxivhisgkzncm"
         "kewphusvaycteennpltuevohegzvafwxuebmovgkpwlgyoutsbbgxoxdzyisersgaqcnn"
         "jnjtjwufqscjzccudbkdcnmorpmraqapvirijlpretmezlrbdvnfixvmalzmgrhwpkhis"
         "aztpsgvlooqxezzscjrtnmmctoyinjermwrrmjlfbizryripnarkvnabdizzereczdnbk"
         "ojpfmxhlfvlztmzpskwttzyusxaudprxpbpihorlipzpdiucpvrqlscmoipvdzsrowjrw"
         "mxzomtcxxehrmcaxmtifcvftywjkzgdsohvomcthhylzpijujfyysbientozyirurugev"
         "ubxpdpbihrudvgdmhwyxuhyorvufffqzifwzszmfswhkesywfyozffzarrklnxppymoas"
         "lqctlfbtrykccmgmhrdacuelfrbflsjxhdagaevscxerljtxnwodtfioyxjoaxyhzjmtt"
         "vflfhqvvcbwvmnulcsubtwngjvomqkqrjtntkzuclolcjmiypjilgvezphjqrjetqnacc"
         "rjmxydmmkbmuyxwotfynptdotuaxpxzgjulwgwfbprzolxablskvidnmnzcofemsodets"
         "iubqrvtbkshuokkuomjezwbmtcjvapnlsmutehyfxaqjqlibfzitcfhuivmmclulnrwyk"
         "nbymyfcwbgyxtavcaebvfwlkikylkrpcfappcamnjenpggoxcrpxdbqjqzrdvnfzxuxua"
         "ixbpiqmitzhefcgyhzayemxgrtdoiryqguiexsrysetobkqnfphdechsgoqvmdhurzhvf"
         "lsbxsdjemmvlzpthrjizfcayxemztvszhhpfvvjgoejrjnmyvxstpejfmiukuocmrgvin"
         "qifpdcqvwfddoiyopbzverxwcqdyoqzeqcjcwmojbhcnrksebanfpdhhpiaguxracnxzt"
         "tbjgruczuhwwjbmznzgdijyemrwcawodqftjtlyozqwwchxtlvlnjqwklmbzirfhaquil"
         "tdijijeglroopaagmyrkhqbnkhbxvguodmmszfoomhfvwjsnrmmzjuyxhotehlezyyipt"
         "zububvazwzziskqagtpthflchvvanpugjpeoipecmvgkocylsqduwbreeifhjdomajmnb"
         "wrmxuhvvjnfblyvtveqalkqlbxkxvmxfefvijptnpvhmgmotrvsxmarhkspdlybniuoxy"
         "cahgisvnrlrukendhsxvvcqzinnbkryzwbnktsgfwxjklrcgvtrzvkqfbhctljoijsvxb"
         "nwiunrasctvuetwvzdulmlnxeivsvujihlmjroxntmgkecjkimcsvfesfeursbuchaexg"
         "pyqakllumehlfdkuzbnulwfdacxjalozmrneqtjvdpgkcwnrkuhhqbnpedmysjqcrdqaa"
         "wiwcucuzlbkwozlgrgcroyebklrwzkqicuqezkswayknmcytcsrtkxkfwxmimpolrqzjw"
         "fdzmlkpinifykobpvqlzqrcliorfqygytfgpdociwflhwpuuumrwnhrkpnteqacxejyul"
         "kccgxtnsfhuuahifvsshkwrkhptqvcmylyvvykwjhgknmsuolomginxdfwvqpfwlpwvom"
         "mjjymsunxmbjxlcznmefzvuckeqfpighnxzxdpdlcifxbzldjctrswxmrxcjbbtivfnwq"
         "elhkmbunsroodysywhjsysajsrngtsvimguuwaicmuqzmafocvdzudgkmmvhydmafxqrr"
         "pkvvnnjyzohjwtjgqbrptggknxpuatfycatgimywhbafhjazjklgzxaiecmqbqgwgdepf"
         "spuxakrowawfolujdcyqsmakrkiqiduitooygdduztcquxqyraxhwjkvybbyiksqyqxqf"
         "myzjyxxrxktmfklcjsjeijjflvtjayqlfuqtacxrfbrsdqtuwmflpdtxtjezsgeoeeyhc"
         "pncbknslbexvicfxslnqbelcfjonoakbitkizdlmusmydyajmiiouvqhhpmjspwoprvaj"
         "ocrloqydqbrgzxqafbfonuvecxjcrpoiorfqxofionzmomccxkhjqzkvpdevkwpsikonj"
         "xfthvtorexdyntvhttbtygzmtrrzprsgqnvbzhxuiruhugtaogfrjqdxnilxatjyltpbc"
         "hjlkajaxefdjjwhqzjeejznbjkhdjqoltccfgosuuxodgyhvufwdrdxtpuvxlthxibekz"
         "kdoufkbstuxhwukrfaqsbratipaaxjawndpognykgltxofqbypomdpdsgncggpoddzbob"
         "loikifupdfgytydhxoxtcyerqpgezsddndikvcwufcefpdkdgvrlmvoiadawofsuyezli"
         "ebpixyqboteavtvqeojxmemrdbptsxdckszxjgveaqngboxfdxqdgddczdzpyhlztthvb"
         "zgutaioqswwpzupddayzktwvqyvxcflmolxyewseqrrvpovpeftwgiywoyflwejpffxpu"
         "bejlwmazjzfcldadgnkkjtmxktuzlocvqhjajqrfrfaloychnmokakwsfkrtacwjgsiep"
         "tnujtgbbwzllvkpeuewegmkchhaaaptmbmoybtdotctkfyumafregkthibmufiudjrcoh"
         "dhuhlpjeishhekicdfiiostjmofwhreoegrnbqgkhmiezgtasdaqdcixsrdfdsfcrgjar"
         "yeqtkussultserwmyealuvxckhcgojsxzsfxmrtcfhqpowalbbzvpcltiwdhexbvcjojd"
         "ptxeplgestsnpmpibymzaolqaybmeezyagvvftcuqgqrpjauxjnmudeasbpeormqofrbm"
         "mgorysyztkbloyfjikxdrytsdfdrjagghbbjqkujemzvvtioluzitrmaxjphducstlear"
         "firqknijfdurdztizvwoeqzamxkbbvmnbxomhsxfmwdhocdyabcygzojqebxferyieqfi"
         "slcpwiaadbarnsgnuvhkaidexxcgxhmvsiwqhoxkjwvycbyaqiddlrgsvqvzkvqzeewbx"
         "nfqlhavmqyucnnlskzyhwlnpglakbstcsnmsipeekjbwvokjjasfcruinzkcmjtkuztng"
         "lqakavnjmvccjgquzfftcqzwnrvywoqxhzbkbjufjuyqqqtaoakzbykeraqalcqzuhjnd"
         "gusnvdanqrwemqsmcwxelogrfxxsdyzlbfuvopxsyzuizshrtauculajiapoentvnkxpv"
         "yfxfecjolvlezsmfmibhptmgdkiucnsralqhtutgvnpzicjwcgrtcgyueuqsxnyspxmnz"
         "hupjwalphkutczrptfxsvgeikwqqhesezmkoliizhceciotrcrjhunyfnpeyrnmucyhko"
         "zbipsmuqfgujshzhzuxextaapmrbhvexaqyifwrodhftkwbpyndylvfukebddabmjperi"
         "mjtzeeqwmjzjxjrqglwcsuxinztzxpzfdlirmyroecjkimmgnybedfhssjfzzdnqlzihf"
         "gobikowitiqdyzlhxbxifamfkeienxqvcmvhzixicqlylurlfnzbrfoztfjxswwlxkvrh"
         "ueccohddaazuluirluhzliuqeqiajvmvtbpibfhiulyagqfowibqjkjewqminwsuupmxn"
         "ijyrbiodfknndgpfiannwlkillxmirfqmmoktexmoqxqujogmxjmkenfphffmdfablsaq"
         "xufjwvmufogrzjarlopjhidbfbhoivkknzgqresjprfknjetohwtqurxyngxilywmbgps"
         "ctswswwkasyisochqeslbiunnbgxsgzwkopnhgdjyuherwtrkypbjrdesztgkxzueqrhh"
         "icwndmidmqahdwcycqpgtuildbowqhjaqnmblbnvvsxahycecvfnbvqzcjburykyjkgaz"
         "gauobvieoerphnehdjxfianvcaasrctenrcwcgzcqbzufwsqllzbxnjzktgermrodlzuv"
         "kdblqcwbfjevjkygbgoalqyibexruhsxsowmchcogiffedbuddithpwocmovwbpvxzhwm"
         "yzpuwdhrorlqxxtqtwswmdcszbxwyirhpwjjulqoovmgqydxctjrnncsfevitouvdvsgd"
         "ftpyjztxrxhuggdtyfandnuvufixthdxidrlzzkssngvrmtkwzifwjoqyawcohqxrucji"
         "xdcrhgybujxpbjfwxunbbotjlijfagrdsbeemkvgaebuagweegcgpoleicaakefhgvgji"
         "slsamatuqmmjisifffwmigqwxaywwmoyzarwtpiimekzofbycyoqznbnqwnncmzoiwpjg"
         "pymvynrgasxpekunmzksdrfxlyxewqmfoeufccrwevhhxxjqzkptkctaqerwotatqgkbn"
         "jqbpfyglucttnmxpxrrjhglbmzzjtyupaexfismwrvfgtunlriabhhyklpmevgmltnkdt"
         "tjmemegytzzikcykidlasvugyzfaozknksednbsdcfnfwtozioavvipvsrkztslcxqgrc"
         "cocxtwnxobbhidcublbnpwhohqjcxwfftmptlwtpjugbchgxahplumbjqjfvljhqzmbds"
         "deemxevugsthrveucyqxdktkdymznwdvkuoytvfrrfzrmlnedhckhngadcpugwzfupcud"
         "mukkpzrtdqvpcpzspuhdfoeojybisjmcjmcyhiiqjnfkcpepbflwfwmorpgwumlzynzpb"
         "bvvrgtxpsgzdelmlohavhyqhrfztmncnllnfdgdotoiojwtwilwwdszhcqbkdwtyrurxk"
         "zgcwrcvqlhynujihfdbwnnhkwdmfwciurvrqkmyghvhftbfhjogfrrslmuzussufwkkie"
         "wfevkvgalhyutnfxzgxbifjhbqolbsanvwkhyfxywfbvxvoiwcqhvdypwpgquutrugldi"
         "zlvqaeeboriznjxovvmbwqyrxmxqilplplszubphmeszzrfjoliuskludoukazpiezpzu"
         "crsiiiichlxthowlcbmmfnyjyylgrcseraqtwodnxvugpysbosancqgzmxinonoeqmvyu"
         "msdwjncgztbepamqupqvxzudrniawehxilhybtdsupswxzjfhhchdeqoidvigjhkonfrd"
         "skxvoskgezzhhcpcfodahrlnkoldcdomllfcywrtqofedeychinhsvcssmgbadabdgyvm"
         "scucbckahgjawopdwlixbkmlxcpxtaqoempcldkefcerzeiowhgyhreveztowuigsgwcv"
         "djahrfvrvvubliwretdwqslwgusqoqcczbzdalaocaarmtqhgjtzjjwnntuezwioelmwx"
         "nvnfeeggjljuybgshzeqsongxutyjovbklauknymkkkmnnwqxixaiwaxfbysglyvazrrc"
         "qcbgepgegwlmtycljiaqivlscezkquxkgzubqnbdsfxditryyagiihyoqdhtudnfmkwao"
         "httygtwesumjjivazppjzkbdywdfudbjkubytrfasxkxqmdgnirqronvypulppeaqbjim"
         "tvffglxvihsvesvhbagtuikytbocsjnxfoxmtwpfwcdadliexyisjopbkqbjhlflqyxnj"
         "dkqndjpbdehwfsljapruwbslzchkyvsmcvocictzqxcktfmoathqnxmlqirfjezhqbbou"
         "pnzlyqmiqiqkkbhwhpcyibipmizzxhlbjffxdzigymhjgyowmrjouvfjwgyzdovyslmfb"
         "plvjnqvfdbfeqvugoqdzvtggrpueutlljsfgudmgrzjqiaghatyzwjbkxxadrwjohhqmn"
         "wrswodapavdwyvwicbignxagbqodjeihgvwbdlexjcrltkidjdzjjteihgwedogtxafma"
         "jjgfgprbtbktqvirgxvvakqhbvgizxdgmabszclfbkrchaubgcobhpqrtfjbjzhpllxyv"
         "uqinnnkzdwqxzjjbniytymygnjzmklhpvazfqcdhafvoxlkxnvsmzfhjcqwdzqmlblhdu"
         "duwbpbwonfmfwwbvhbgoyhwlmlxfnhlfpzwiybgeqghufeqilmdxzcdwrdwiculhnhzxy"
         "bxvkwpjbwyprvtphhhqsnukanpnzoxtumxwlgostwbgqmtvdzsecquyrircmlckkzvicz"
         "rvtkzyazlihddrlohyrovhprvcsmjrbxjaivvgolidxbyvxgkflallznsylhuzrkhrvfa"
         "kpbhwhrgtwnlczewkyxhcturbfbfvlwvhaykumdftqbkmdxutbnphdsgplxxsdkcfouap"
         "rhecugnzdsjdyjkkuvtjtberlrwxhddmshcoyzlrgwugpnozubiglbcjwxjnvnmnbdtvl"
         "fbqqijwmdkrzslhsvnxnrsdbkbyxfkluvtofyesakxclxvodsuxwlyqkoyhynxfmpvmec"
         "qxxasvmsdrandljnyeepxaiwdvmmrzxstnzzfkxjsflkkrabqkicjutpyrbaewqzwfwdh"
         "zjqibmqhhzbnoaucsbpjtvvumkpaehnxxsjgkfpbfannzznhylowtsnilprqrbohrmcuc"
         "boxzqwnbkbkgldydkqqqgjbtxavejjlxfqweybeaczszapiqiqoqwzhrvnjlmjmdmyyzi"
         "qcusbpyxqwetclyrhfjrgzxbydajuqnbxhmjgenskqjikmgqlpbmsvuuxehfbydyqvgdf"
         "nkdqhlptgaollttiduybwqgaaatmcvdhagbusjrjigyhcphyhowixnezvioigsjdosikt"
         "hzijrdvsfabprlcmjtjekculxcoyvypsozolqezlgunkhsftyjrffpfkuxbuoolragvar"
         "mtjozwqfiqdlaldxdauwzdrlhxlghtovdwesahmzklfoywukjufdiyiepnyjqzqbvomve"
         "faahlnbgjhvumffksfvomrbnfstssvdgpubtmglxicclsijqumvibauoaxvgteljaajfc"
         "rqadkxbqrgbwaihxdsaisopmmwbzddapbczwnfnxspgtajjswcubnspwxglemattdgijk"
         "avsoanafyrkczcvmxzciuvtiwnraibtfrdqcntksioxjlzstxivizavgurmvwphdfxcvw"
         "qicctqicommgehtlunpbknkkklbzcjrxcxjchbszlqhtcdkzbdktkffbbwufcvscjsara"
         "ktaatyexzjxvxvoyyzivxpmwuxxkjdkrrmfegzkevmaeotwvpcrjtbfsblfdebacvomgt"
         "udrlcrjktvwdaerlafaqfcopbqxujngvxmjelcuesauyxuazrhiztlapgvsdenyqpafck"
         "jzohjjbdosjyvombptrppmanummqvahchtqkjdppwwskbygzaqpjlxkiposgfwltwlkvo"
         "wynkcytprknckyppzvjjqaqibhakstpgkpbhviuqdrnsazdfptdmheqeusmkskdldaqnx"
         "thokukmhcpssjrtjnemyvlsaeryoeiclipnrjmbiyzpzfprjeyhphuqtdgqsgmicalezp"
         "yoakygeorrhzuyzhqqddhrygeybtoanobkvbfgpchrbtqbampimgefkyrkdfqgwyulvqb"
         "zljzbrisjugfjpruwilxneypgflzfldsbkpymcmxfpedmwogtxqrifposbwmohakknpkd"
         "bdycsgetahejtlqjaoumqyjbxywbmpbtcgquedhtfbbptomabbnahguvzsayqgvqxolvu"
         "flfjfhvmilqdzwqusvlcgemlaouwlgluuqtrqlhwooretsjjtnpnvrpnicakqcfuxotzm"
         "vqhsvoptvqiletevbhfbrolhijwidauovqlnqwmwvfoxljrbjtbwuazkhpnxntigrbdlh"
         "wbtwtzlnginyooppgpilsuzzjvfhanrggtxcjfxmvgbfsipktduomcoukthptkxahkkiv"
         "mbnikapysfahapdembxvuakdniziuslabaotlifsolqboplhuasrlawpjsjaheapmubdt"
         "ysalursciiukkgtrkzmqaltyksvdmomgydqqswpkqmewzzyxifqiivisommszulngjdso"
         "vkgsahicjhnlxqutcsyhfhxxyamenvwbruzzkywgmcmnqzvkindlsworliooqshsbxvoc"
         "trjionbzsihjhfitybhqyajludzdmitakuritzrgpdkvqptsmrqojcagmrhjppgsovqgr"
         "gjzdpzmjcrjbqprzbuufhwjlfgjwokimhvihgkgnkuajkpfsbiragdwbggbjesipyihpi"
         "nhcrhpobdiaasfdivbsjpqeobgbzszqdkoixnhihncdutlggytzukcbtrdvxgbdllkswa"
         "rjqehcdddgqdvwxgjtyymecyvqsutnpnwygxvlxxrpggidpmoygidulrdnixkuuiwmigc"
         "sntnlvomivajdmmopbyqljbmkqueawblhaicmshjhwnxieiftzjwwrwameuuzcoqiuibp"
         "csaajzdciyxsqaeubgixinvwlecbkrctrwtoskgbdjbyjlgvmydlqrymdhyfdqawurvxp"
         "rrnfnymfuvenrfdwpnxfqsbylqfokjnmpvnrtoqnhzpgzsebieouetuuruwenrjbuwond"
         "epkkuvxfzyswbnlykxglazitalhyhtksszzhglorprfobxkihnwxghhybaaspqmucv\")"
         " -> "
      << s.checkInclusion(
             s1,
             "jpdojwinknmyeorfdhpsysyealozhgbapagzjsivbxmcyijlbdafupblrawguoazu"
             "zcqupobxayrkpqxawytdsdznljnxulaugewrbjmkslsrllixpkuvorhnnhkzikovs"
             "ajrbhjdybocvjloqiikidsnwcubhliajwwqkpqaugidhfxqfxrkluvadcdmekdhck"
             "szpojvwpiquazmaecaxxwsnswzxbctqeqhjsrgnjsjmaqbexexuwgfglixsthifev"
             "okdgexxkdmzaxrcilmthzemuomexwzipzivdyxqnvgzpjavonrkobmgkormdmfiww"
             "algdzwlngkrjmdwkknajqatghoddybqfkorhpmrkfcfwsaproaenfedvfendprnlp"
             "muqklsqrsjuejyxulfuhdsyolthhhfhmxorojnjsvqyworupkdzhyqkzikvhltfsr"
             "hrecmyyddtinphjsmmbdtrouyifvsvvlamwhkffrrywdiawpvxwcwfkcunbjaelbc"
             "mdwczikkfelahowtbwqbdcjggnmknfhjdtusfjotsbjgtlnuonlxjlcwyqiffkton"
             "vtrkcogosfbcvcosktnvbeitxuqpexxejnklndzbtzlzeebwufoiwqqcoemnshcpo"
             "vntjgidophekyntcsrwzvovwmostqudxgeaowehcmqmdrllovmmbgqhaxrqluizhh"
             "hslystwkhckjtosnomfvyibkasycxnnmvkbwkbhzeayezughsmqovogrnihjgetsd"
             "vhymjmnijzwvpasurcaybmyzfbqepjsdqwmkmomzkociaqtnkwiguylhwxrfamyxj"
             "vfxwonwblidvcsenvwigjjqdsnnydlgdhlsdtonvuapzaozkdtyiartimmpwgotnw"
             "piwimbdunqfickerusbvrqwazvnwgdczvnqtigjmkjgsridfulxjekazzqkdynyuu"
             "tyoffhntfbcruhrmnhhjyyzfszbaqykgnroepiovqqlhdtkizvpivukdutitwzhap"
             "vcyfghqvtjyyrdbctvdccoxjtsovdosbyqaiffumnrfokrbgvedxbcytvbcaeoviu"
             "tdmxwfhxgchnusazcztitxgyjrkjdmajbndlemsnpjwzgvpitrfrjoxivhisgkznc"
             "mkewphusvaycteennpltuevohegzvafwxuebmovgkpwlgyoutsbbgxoxdzyisersg"
             "aqcnnjnjtjwufqscjzccudbkdcnmorpmraqapvirijlpretmezlrbdvnfixvmalzm"
             "grhwpkhisaztpsgvlooqxezzscjrtnmmctoyinjermwrrmjlfbizryripnarkvnab"
             "dizzereczdnbkojpfmxhlfvlztmzpskwttzyusxaudprxpbpihorlipzpdiucpvrq"
             "lscmoipvdzsrowjrwmxzomtcxxehrmcaxmtifcvftywjkzgdsohvomcthhylzpiju"
             "jfyysbientozyirurugevubxpdpbihrudvgdmhwyxuhyorvufffqzifwzszmfswhk"
             "esywfyozffzarrklnxppymoaslqctlfbtrykccmgmhrdacuelfrbflsjxhdagaevs"
             "cxerljtxnwodtfioyxjoaxyhzjmttvflfhqvvcbwvmnulcsubtwngjvomqkqrjtnt"
             "kzuclolcjmiypjilgvezphjqrjetqnaccrjmxydmmkbmuyxwotfynptdotuaxpxzg"
             "julwgwfbprzolxablskvidnmnzcofemsodetsiubqrvtbkshuokkuomjezwbmtcjv"
             "apnlsmutehyfxaqjqlibfzitcfhuivmmclulnrwyknbymyfcwbgyxtavcaebvfwlk"
             "ikylkrpcfappcamnjenpggoxcrpxdbqjqzrdvnfzxuxuaixbpiqmitzhefcgyhzay"
             "emxgrtdoiryqguiexsrysetobkqnfphdechsgoqvmdhurzhvflsbxsdjemmvlzpth"
             "rjizfcayxemztvszhhpfvvjgoejrjnmyvxstpejfmiukuocmrgvinqifpdcqvwfdd"
             "oiyopbzverxwcqdyoqzeqcjcwmojbhcnrksebanfpdhhpiaguxracnxzttbjgrucz"
             "uhwwjbmznzgdijyemrwcawodqftjtlyozqwwchxtlvlnjqwklmbzirfhaquiltdij"
             "ijeglroopaagmyrkhqbnkhbxvguodmmszfoomhfvwjsnrmmzjuyxhotehlezyyipt"
             "zububvazwzziskqagtpthflchvvanpugjpeoipecmvgkocylsqduwbreeifhjdoma"
             "jmnbwrmxuhvvjnfblyvtveqalkqlbxkxvmxfefvijptnpvhmgmotrvsxmarhkspdl"
             "ybniuoxycahgisvnrlrukendhsxvvcqzinnbkryzwbnktsgfwxjklrcgvtrzvkqfb"
             "hctljoijsvxbnwiunrasctvuetwvzdulmlnxeivsvujihlmjroxntmgkecjkimcsv"
             "fesfeursbuchaexgpyqakllumehlfdkuzbnulwfdacxjalozmrneqtjvdpgkcwnrk"
             "uhhqbnpedmysjqcrdqaawiwcucuzlbkwozlgrgcroyebklrwzkqicuqezkswayknm"
             "cytcsrtkxkfwxmimpolrqzjwfdzmlkpinifykobpvqlzqrcliorfqygytfgpdociw"
             "flhwpuuumrwnhrkpnteqacxejyulkccgxtnsfhuuahifvsshkwrkhptqvcmylyvvy"
             "kwjhgknmsuolomginxdfwvqpfwlpwvommjjymsunxmbjxlcznmefzvuckeqfpighn"
             "xzxdpdlcifxbzldjctrswxmrxcjbbtivfnwqelhkmbunsroodysywhjsysajsrngt"
             "svimguuwaicmuqzmafocvdzudgkmmvhydmafxqrrpkvvnnjyzohjwtjgqbrptggkn"
             "xpuatfycatgimywhbafhjazjklgzxaiecmqbqgwgdepfspuxakrowawfolujdcyqs"
             "makrkiqiduitooygdduztcquxqyraxhwjkvybbyiksqyqxqfmyzjyxxrxktmfklcj"
             "sjeijjflvtjayqlfuqtacxrfbrsdqtuwmflpdtxtjezsgeoeeyhcpncbknslbexvi"
             "cfxslnqbelcfjonoakbitkizdlmusmydyajmiiouvqhhpmjspwoprvajocrloqydq"
             "brgzxqafbfonuvecxjcrpoiorfqxofionzmomccxkhjqzkvpdevkwpsikonjxfthv"
             "torexdyntvhttbtygzmtrrzprsgqnvbzhxuiruhugtaogfrjqdxnilxatjyltpbch"
             "jlkajaxefdjjwhqzjeejznbjkhdjqoltccfgosuuxodgyhvufwdrdxtpuvxlthxib"
             "ekzkdoufkbstuxhwukrfaqsbratipaaxjawndpognykgltxofqbypomdpdsgncggp"
             "oddzbobloikifupdfgytydhxoxtcyerqpgezsddndikvcwufcefpdkdgvrlmvoiad"
             "awofsuyezliebpixyqboteavtvqeojxmemrdbptsxdckszxjgveaqngboxfdxqdgd"
             "dczdzpyhlztthvbzgutaioqswwpzupddayzktwvqyvxcflmolxyewseqrrvpovpef"
             "twgiywoyflwejpffxpubejlwmazjzfcldadgnkkjtmxktuzlocvqhjajqrfrfaloy"
             "chnmokakwsfkrtacwjgsieptnujtgbbwzllvkpeuewegmkchhaaaptmbmoybtdotc"
             "tkfyumafregkthibmufiudjrcohdhuhlpjeishhekicdfiiostjmofwhreoegrnbq"
             "gkhmiezgtasdaqdcixsrdfdsfcrgjaryeqtkussultserwmyealuvxckhcgojsxzs"
             "fxmrtcfhqpowalbbzvpcltiwdhexbvcjojdptxeplgestsnpmpibymzaolqaybmee"
             "zyagvvftcuqgqrpjauxjnmudeasbpeormqofrbmmgorysyztkbloyfjikxdrytsdf"
             "drjagghbbjqkujemzvvtioluzitrmaxjphducstlearfirqknijfdurdztizvwoeq"
             "zamxkbbvmnbxomhsxfmwdhocdyabcygzojqebxferyieqfislcpwiaadbarnsgnuv"
             "hkaidexxcgxhmvsiwqhoxkjwvycbyaqiddlrgsvqvzkvqzeewbxnfqlhavmqyucnn"
             "lskzyhwlnpglakbstcsnmsipeekjbwvokjjasfcruinzkcmjtkuztnglqakavnjmv"
             "ccjgquzfftcqzwnrvywoqxhzbkbjufjuyqqqtaoakzbykeraqalcqzuhjndgusnvd"
             "anqrwemqsmcwxelogrfxxsdyzlbfuvopxsyzuizshrtauculajiapoentvnkxpvyf"
             "xfecjolvlezsmfmibhptmgdkiucnsralqhtutgvnpzicjwcgrtcgyueuqsxnyspxm"
             "nzhupjwalphkutczrptfxsvgeikwqqhesezmkoliizhceciotrcrjhunyfnpeyrnm"
             "ucyhkozbipsmuqfgujshzhzuxextaapmrbhvexaqyifwrodhftkwbpyndylvfukeb"
             "ddabmjperimjtzeeqwmjzjxjrqglwcsuxinztzxpzfdlirmyroecjkimmgnybedfh"
             "ssjfzzdnqlzihfgobikowitiqdyzlhxbxifamfkeienxqvcmvhzixicqlylurlfnz"
             "brfoztfjxswwlxkvrhueccohddaazuluirluhzliuqeqiajvmvtbpibfhiulyagqf"
             "owibqjkjewqminwsuupmxnijyrbiodfknndgpfiannwlkillxmirfqmmoktexmoqx"
             "qujogmxjmkenfphffmdfablsaqxufjwvmufogrzjarlopjhidbfbhoivkknzgqres"
             "jprfknjetohwtqurxyngxilywmbgpsctswswwkasyisochqeslbiunnbgxsgzwkop"
             "nhgdjyuherwtrkypbjrdesztgkxzueqrhhicwndmidmqahdwcycqpgtuildbowqhj"
             "aqnmblbnvvsxahycecvfnbvqzcjburykyjkgazgauobvieoerphnehdjxfianvcaa"
             "srctenrcwcgzcqbzufwsqllzbxnjzktgermrodlzuvkdblqcwbfjevjkygbgoalqy"
             "ibexruhsxsowmchcogiffedbuddithpwocmovwbpvxzhwmyzpuwdhrorlqxxtqtws"
             "wmdcszbxwyirhpwjjulqoovmgqydxctjrnncsfevitouvdvsgdftpyjztxrxhuggd"
             "tyfandnuvufixthdxidrlzzkssngvrmtkwzifwjoqyawcohqxrucjixdcrhgybujx"
             "pbjfwxunbbotjlijfagrdsbeemkvgaebuagweegcgpoleicaakefhgvgjislsamat"
             "uqmmjisifffwmigqwxaywwmoyzarwtpiimekzofbycyoqznbnqwnncmzoiwpjgpym"
             "vynrgasxpekunmzksdrfxlyxewqmfoeufccrwevhhxxjqzkptkctaqerwotatqgkb"
             "njqbpfyglucttnmxpxrrjhglbmzzjtyupaexfismwrvfgtunlriabhhyklpmevgml"
             "tnkdttjmemegytzzikcykidlasvugyzfaozknksednbsdcfnfwtozioavvipvsrkz"
             "tslcxqgrccocxtwnxobbhidcublbnpwhohqjcxwfftmptlwtpjugbchgxahplumbj"
             "qjfvljhqzmbdsdeemxevugsthrveucyqxdktkdymznwdvkuoytvfrrfzrmlnedhck"
             "hngadcpugwzfupcudmukkpzrtdqvpcpzspuhdfoeojybisjmcjmcyhiiqjnfkcpep"
             "bflwfwmorpgwumlzynzpbbvvrgtxpsgzdelmlohavhyqhrfztmncnllnfdgdotoio"
             "jwtwilwwdszhcqbkdwtyrurxkzgcwrcvqlhynujihfdbwnnhkwdmfwciurvrqkmyg"
             "hvhftbfhjogfrrslmuzussufwkkiewfevkvgalhyutnfxzgxbifjhbqolbsanvwkh"
             "yfxywfbvxvoiwcqhvdypwpgquutrugldizlvqaeeboriznjxovvmbwqyrxmxqilpl"
             "plszubphmeszzrfjoliuskludoukazpiezpzucrsiiiichlxthowlcbmmfnyjyylg"
             "rcseraqtwodnxvugpysbosancqgzmxinonoeqmvyumsdwjncgztbepamqupqvxzud"
             "rniawehxilhybtdsupswxzjfhhchdeqoidvigjhkonfrdskxvoskgezzhhcpcfoda"
             "hrlnkoldcdomllfcywrtqofedeychinhsvcssmgbadabdgyvmscucbckahgjawopd"
             "wlixbkmlxcpxtaqoempcldkefcerzeiowhgyhreveztowuigsgwcvdjahrfvrvvub"
             "liwretdwqslwgusqoqcczbzdalaocaarmtqhgjtzjjwnntuezwioelmwxnvnfeegg"
             "jljuybgshzeqsongxutyjovbklauknymkkkmnnwqxixaiwaxfbysglyvazrrcqcbg"
             "epgegwlmtycljiaqivlscezkquxkgzubqnbdsfxditryyagiihyoqdhtudnfmkwao"
             "httygtwesumjjivazppjzkbdywdfudbjkubytrfasxkxqmdgnirqronvypulppeaq"
             "bjimtvffglxvihsvesvhbagtuikytbocsjnxfoxmtwpfwcdadliexyisjopbkqbjh"
             "lflqyxnjdkqndjpbdehwfsljapruwbslzchkyvsmcvocictzqxcktfmoathqnxmlq"
             "irfjezhqbboupnzlyqmiqiqkkbhwhpcyibipmizzxhlbjffxdzigymhjgyowmrjou"
             "vfjwgyzdovyslmfbplvjnqvfdbfeqvugoqdzvtggrpueutlljsfgudmgrzjqiagha"
             "tyzwjbkxxadrwjohhqmnwrswodapavdwyvwicbignxagbqodjeihgvwbdlexjcrlt"
             "kidjdzjjteihgwedogtxafmajjgfgprbtbktqvirgxvvakqhbvgizxdgmabszclfb"
             "krchaubgcobhpqrtfjbjzhpllxyvuqinnnkzdwqxzjjbniytymygnjzmklhpvazfq"
             "cdhafvoxlkxnvsmzfhjcqwdzqmlblhduduwbpbwonfmfwwbvhbgoyhwlmlxfnhlfp"
             "zwiybgeqghufeqilmdxzcdwrdwiculhnhzxybxvkwpjbwyprvtphhhqsnukanpnzo"
             "xtumxwlgostwbgqmtvdzsecquyrircmlckkzviczrvtkzyazlihddrlohyrovhprv"
             "csmjrbxjaivvgolidxbyvxgkflallznsylhuzrkhrvfakpbhwhrgtwnlczewkyxhc"
             "turbfbfvlwvhaykumdftqbkmdxutbnphdsgplxxsdkcfouaprhecugnzdsjdyjkku"
             "vtjtberlrwxhddmshcoyzlrgwugpnozubiglbcjwxjnvnmnbdtvlfbqqijwmdkrzs"
             "lhsvnxnrsdbkbyxfkluvtofyesakxclxvodsuxwlyqkoyhynxfmpvmecqxxasvmsd"
             "randljnyeepxaiwdvmmrzxstnzzfkxjsflkkrabqkicjutpyrbaewqzwfwdhzjqib"
             "mqhhzbnoaucsbpjtvvumkpaehnxxsjgkfpbfannzznhylowtsnilprqrbohrmcucb"
             "oxzqwnbkbkgldydkqqqgjbtxavejjlxfqweybeaczszapiqiqoqwzhrvnjlmjmdmy"
             "yziqcusbpyxqwetclyrhfjrgzxbydajuqnbxhmjgenskqjikmgqlpbmsvuuxehfby"
             "dyqvgdfnkdqhlptgaollttiduybwqgaaatmcvdhagbusjrjigyhcphyhowixnezvi"
             "oigsjdosikthzijrdvsfabprlcmjtjekculxcoyvypsozolqezlgunkhsftyjrffp"
             "fkuxbuoolragvarmtjozwqfiqdlaldxdauwzdrlhxlghtovdwesahmzklfoywukju"
             "fdiyiepnyjqzqbvomvefaahlnbgjhvumffksfvomrbnfstssvdgpubtmglxicclsi"
             "jqumvibauoaxvgteljaajfcrqadkxbqrgbwaihxdsaisopmmwbzddapbczwnfnxsp"
             "gtajjswcubnspwxglemattdgijkavsoanafyrkczcvmxzciuvtiwnraibtfrdqcnt"
             "ksioxjlzstxivizavgurmvwphdfxcvwqicctqicommgehtlunpbknkkklbzcjrxcx"
             "jchbszlqhtcdkzbdktkffbbwufcvscjsaraktaatyexzjxvxvoyyzivxpmwuxxkjd"
             "krrmfegzkevmaeotwvpcrjtbfsblfdebacvomgtudrlcrjktvwdaerlafaqfcopbq"
             "xujngvxmjelcuesauyxuazrhiztlapgvsdenyqpafckjzohjjbdosjyvombptrppm"
             "anummqvahchtqkjdppwwskbygzaqpjlxkiposgfwltwlkvowynkcytprknckyppzv"
             "jjqaqibhakstpgkpbhviuqdrnsazdfptdmheqeusmkskdldaqnxthokukmhcpssjr"
             "tjnemyvlsaeryoeiclipnrjmbiyzpzfprjeyhphuqtdgqsgmicalezpyoakygeorr"
             "hzuyzhqqddhrygeybtoanobkvbfgpchrbtqbampimgefkyrkdfqgwyulvqbzljzbr"
             "isjugfjpruwilxneypgflzfldsbkpymcmxfpedmwogtxqrifposbwmohakknpkdbd"
             "ycsgetahejtlqjaoumqyjbxywbmpbtcgquedhtfbbptomabbnahguvzsayqgvqxol"
             "vuflfjfhvmilqdzwqusvlcgemlaouwlgluuqtrqlhwooretsjjtnpnvrpnicakqcf"
             "uxotzmvqhsvoptvqiletevbhfbrolhijwidauovqlnqwmwvfoxljrbjtbwuazkhpn"
             "xntigrbdlhwbtwtzlnginyooppgpilsuzzjvfhanrggtxcjfxmvgbfsipktduomco"
             "ukthptkxahkkivmbnikapysfahapdembxvuakdniziuslabaotlifsolqboplhuas"
             "rlawpjsjaheapmubdtysalursciiukkgtrkzmqaltyksvdmomgydqqswpkqmewzzy"
             "xifqiivisommszulngjdsovkgsahicjhnlxqutcsyhfhxxyamenvwbruzzkywgmcm"
             "nqzvkindlsworliooqshsbxvoctrjionbzsihjhfitybhqyajludzdmitakuritzr"
             "gpdkvqptsmrqojcagmrhjppgsovqgrgjzdpzmjcrjbqprzbuufhwjlfgjwokimhvi"
             "hgkgnkuajkpfsbiragdwbggbjesipyihpinhcrhpobdiaasfdivbsjpqeobgbzszq"
             "dkoixnhihncdutlggytzukcbtrdvxgbdllkswarjqehcdddgqdvwxgjtyymecyvqs"
             "utnpnwygxvlxxrpggidpmoygidulrdnixkuuiwmigcsntnlvomivajdmmopbyqljb"
             "mkqueawblhaicmshjhwnxieiftzjwwrwameuuzcoqiuibpcsaajzdciyxsqaeubgi"
             "xinvwlecbkrctrwtoskgbdjbyjlgvmydlqrymdhyfdqawurvxprrnfnymfuvenrfd"
             "wpnxfqsbylqfokjnmpvnrtoqnhzpgzsebieouetuuruwenrjbuwondepkkuvxfzys"
             "wbnlykxglazitalhyhtksszzhglorprfobxkihnwxghhybaaspqmucv")
      << '\n';

  return 0;
}
